version: "3.7"
services:
  db:
    container_name: db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: server_db
  app:
    build: .
    volumes:
      - ./dev.db:/app/dev.db
    restart: unless-stopped
    depends_on:
      - db
  
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   depends_on:
  #     - db
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"

